version: '3.8'

networks:
  monitoring:

volumes:
  prometheus_data: {}

services:
  grafana:
    build: './grafanaConfig'
    ports:
      - "9091:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
